### ISSUE TITLE
有关输入分辨率的问题

### ISSUE THREAD

**Issue by maxqiqq** [nachifur/DMTN#1]
您好！我是电影技术专业的一名研究生，对于CNN网络并不十分了解。
目前想要通过智能去除阴影算法，解决材质捕捉流程中的问题。
请问，如果利用您的代码输入更高分辨率图像（材质贴图至少1024^2）会产生怎样的结果？
如果您你能抽出时间回答，不胜感激。

**Comment by nachifur** [comment]
1024需要重新训练网络的

**Comment by maxqiqq** [comment]
好的，感谢回复。
