### ISSUE TITLE
SRD Dataset Issue-DSFC* files are missed

### ISSUE THREAD

**Issue by lime-j** [nachifur/DMTN#2]
Dear author,
Hello! Great work! I find that the released version of the SRD  dataset (https://drive.google.com/file/d/1GTi4BmQ0SJ7diDMmf-b7x2VismmXtfTo/view) seems to be different from the original one (The file name of DHAN's extracted mask on the test set is different from this test set). Could you please share your version of the test-set? Thanks!

**Comment by nachifur** [comment]
Rename and delete `_free`?

**Comment by lime-j** [comment]
Actually, DSFC* files are missed

**Comment by nachifur** [comment]
In fact, the link (https://drive.google.com/file/d/1GTi4BmQ0SJ7diDMmf-b7x2VismmXtfTo/view) does not contain DSFC* files.

**Comment by lime-j** [comment]
That is exactly the issue. Your released SRD result (as long as many previous works) has DSFC* images, but the released SRD dataset (the Google drive link is for https://liangqiong.github.io/publications/) doesn't. That's why I turn to your help.

**Comment by nachifur** [comment]
Thank you for your feedback, I have found the problem and contacted the original author (CVPR17-SRD). I will let you know if I hear anything.

**Comment by lime-j** [comment]
Many thanks!

**Comment by nachifur** [comment]
See https://liangqiong.github.io/publications/.

Test dataset (SRD): https://hkuhk-my.sharepoint.com/personal/liangqqu_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fliangqqu%5Fhku%5Fhk%2FDocuments%2Fshared%5Fdataset%2FIllumination%2FSRD%5Ftest&ga=1

**Comment by lime-j** [comment]
Thanks for your reply!
