### ISSUE TITLE
在哪加载与训练权重

### ISSUE THREAD

**Issue by zhuxiuh** [nachifur/DMTN#4]
你好，我尝试使用你开源的代码与权重进行测试，发现效果与你原文的不同，能冒昧问下是我哪里操作错误嘛？
输入图像
![91-8](https://github.com/user-attachments/assets/14b251fc-2def-435a-a85b-0d3fdd7e720c)
预测结果输出
![91-8](https://github.com/user-attachments/assets/6c648a18-79f9-416e-a9cf-3fdc2f84900a)

**Comment by nachifur** [comment]
没有遇到这个问题，你可以自己debug一下

**Comment by zhuxiuh** [comment]
感谢你的回复！我通过debug查看了网络的输入是没有问题的，然后网络输出就变成了这样，我害怕我不小心修改了源模型，还重新下载了源码，仍是这样的。那可能只能debug看一下哪一层输出有问题了

**Comment by HighColdMan** [comment]
我也遇到类似的问题 找了好久到底是在哪加载与训练权重的

**Comment by nachifur** [comment]
https://github.com/nachifur/DMTN/blob/2c47ce064cecaad67fb0ceaa45b443a010dffddd/src/main.py#L42

https://github.com/nachifur/DMTN/blob/2c47ce064cecaad67fb0ceaa45b443a010dffddd/src/model_top.py#L131

https://github.com/nachifur/DMTN/blob/2c47ce064cecaad67fb0ceaa45b443a010dffddd/src/models.py#L19
